#!/bin/sh

# Define custom names for the workspaces
CUSTOM_NAMES='["一", "二", "三", "四", "五", "六", "七", "八", "九"]'

# Retrieve workspace information
workspaces() {
	ACTIVE=$(hyprctl activeworkspace -j | jq '.id')

	WORKSPACE_INFO=$(hyprctl workspaces -j |
                     jq --arg active "$ACTIVE" 'map({id: .id, windows: .windows, monitor: .monitorID, active:$active}) | map(select(.id | tonumber > 0)) ')

    TEMPLATE=$(seq 1 9 | jq -n --arg active "$ACTIVE" '[inputs | {id: ., windows: 0, monitor: -1, active:$active}]')

    jq -n -Mc --argjson info "$WORKSPACE_INFO" --argjson template "$TEMPLATE" --argjson names "$CUSTOM_NAMES" \
              '$info as $winfo | $template as $miss |
               ($winfo + $miss) | group_by(.id) | map(.[0]) |
               map(. + {name: ($names[.id - 1] // "Unnamed")})'
}

workspaces
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
	workspaces
done
