#!/bin/sh

# Get current clocked TODO from emacsclient
emacsclient --eval '
(if (and (fboundp '\''org-clocking-p) (org-clocking-p))
    (format "%s (%s)"
            org-clock-heading
            (org-format-time-string "%H:%M" org-clock-start-time))
  "No ongoing task")' | sed 's/^"//;s/"$//'
